language: ruby
os: linux
dist: bionic
before_install:
  - export ROOT_DIR=`pwd`
  - export NEKSTAB_SOURCE_ROOT=$ROOT_DIR
  - export PATH=$NEKSTAB_SOURCE_ROOT/Nek5000/bin:$PATH
  - sudo apt-get -y install libmpich-dev mpich libopenblas-dev
addons:
  apt:
    update: true

env:
  global:
    - MAKEFLAGS="-j 2"

install: true

script:

  - cd examples/1cyl
  - ./cmpile.sh all
  - nekbmpi 1cyl 2
  - tail -f logfile
