language: fortran

sudo: required

before_install:
  - export ROOT_DIR=`pwd`
  - export NEKSTAB_SOURCE_ROOT=$ROOT_DIR

  - sudo apt-get update -qq
  - sudo apt-get install -y libmpich-dev mpich libopenblas-dev

install: true

script:

  - git clone --depth=50 https://github.com/ricardofrantz/Nek5000.git
  - cd Nek5000;  git checkout -b v19 5afb617; cd ..
  - cd examples/1cyl
  - ./cmpile.sh all
  - nekbmpi 1cyl 2




