language: fortran

sudo: required

before_install:
  - export ROOT_DIR=`pwd`
  - export NEKSTAB_SOURCE_ROOT=$ROOT_DIR

  - sudo apt-get update -qq
  - sudo apt-get install -y libmpich-dev mpich libopenblas-dev

install: true

script:

  - cd examples/1cyl
  - ./cmpile.sh all
  - nekbmpi 1cyl 2
  - tail -f logfile
