#!/bin/bash

function error_quit {
    echo -e "$@"
    echo
    echo -e 'Usage:'
    echo -e './compile_script <case> --clean'
    echo -e '   To clean build direcrtory. Makenek will ask for cleaning 3rd-party libraries.'
    echo
    echo -e './compile_script <case> --all'
    echo -e '   To compile the code.'
    exit 1
}

#parameters
export CASE=$1
shift
export SOURCE_ROOT="$HOME/nekStab/Nek5000"
export FC="mpif90"
export CC="mpicc"
export FFLAGS="-I./inc_src -g"
export CFLAGS="-I./inc_src"
export PPLIST=""
export USR="frame.o mntrlog_block.o mntrlog.o mntrtmr_block.o mntrtmr.o rprm_block.o rprm.o math_tools.o"
USR+=" io_tools_block.o io_tools.o otd_tools.o otd.o linalg.o"
export USR_LFLAGS=" -framework Accelerate"

LD="$FC"

# arguments
args=("$@")
argsnr=$#

# check arguments
# parameters number check
if [ $[argsnr] -ne 1 ]; then
    error_quit 'Wrong arguments number!'
fi

for il in "$@"
do
case $il in
        --clean)
                ${SOURCE_ROOT}/bin/makenek clean
                shift
                ;;
        --all)
                ${SOURCE_ROOT}/bin/makenek ${CASE}
                shift
                ;;
        *) 
                error_quit 'Wrong argument.'
                ;;
esac
done
