"""evidence_report.py — Report missing, stale, and contradictory evidence across the catalog.

Usage:
    python3 scripts/evidence_report.py [--json] [--strict] [--stale-days N] [--catalog-root PATH]

Exit codes:
    0  No issues (or issues found but --strict not set)
    1  MISSING or CONTRADICTORY findings found (only with --strict)
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import sys
import time
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from validation.catalog import MethodCase


def _resolve_catalog_root(explicit: str | None) -> Path:
    """Default: parent of the directory containing this script (= repo root)."""
    if explicit:
        return Path(explicit).resolve()
    return Path(__file__).resolve().parent.parent


def collect_findings(
    cases: list["MethodCase"],
    catalog_root: Path,
    stale_days: int = 90,
) -> list[dict]:
    """Inspect each case's evidence requirements and return a list of finding dicts.

    Each dict has keys:
        case_id, flow_family, role, issue (MISSING|STALE|CONTRADICTORY), artifact_path
    """
    from validation.catalog import CaseStatus, EvidenceRole

    now = time.time()
    stale_threshold = stale_days * 86400
    findings: list[dict] = []

    for case in cases:
        # Build role -> Artifact mapping from declared artifacts
        artifact_by_role: dict[EvidenceRole, object] = {
            art.role: art for art in case.artifacts
        }

        for req in case.evidence_requirements:
            role = req.role
            artifact = artifact_by_role.get(role)

            if artifact is None:
                # No artifact declared for this role
                if req.required:
                    findings.append(
                        dict(
                            case_id=case.case_id,
                            flow_family=case.flow_family,
                            role=role.value,
                            issue="MISSING",
                            artifact_path=None,
                        )
                    )
                continue

            # Artifact declared — check if file exists on disk
            full_path = catalog_root / artifact.path

            if not full_path.exists():
                if req.required:
                    issue = (
                        "CONTRADICTORY"
                        if case.status == CaseStatus.VALIDATED
                        else "MISSING"
                    )
                    findings.append(
                        dict(
                            case_id=case.case_id,
                            flow_family=case.flow_family,
                            role=role.value,
                            issue=issue,
                            artifact_path=str(artifact.path),
                        )
                    )
            else:
                # File exists — check freshness
                stale = False
                if artifact.freshness == "stale":
                    stale = True
                else:
                    mtime = full_path.stat().st_mtime
                    if (now - mtime) > stale_threshold:
                        stale = True
                if stale:
                    findings.append(
                        dict(
                            case_id=case.case_id,
                            flow_family=case.flow_family,
                            role=role.value,
                            issue="STALE",
                            artifact_path=str(artifact.path),
                        )
                    )

        # Check evidence_prereqs (glob patterns relative to catalog_root)
        if case.status == CaseStatus.VALIDATED:
            for prereq_pattern in case.evidence_prereqs:
                full_pattern = str(catalog_root / prereq_pattern)
                matches = glob.glob(full_pattern)
                if not matches:
                    findings.append(
                        dict(
                            case_id=case.case_id,
                            flow_family=case.flow_family,
                            role="prereq",
                            issue="CONTRADICTORY",
                            artifact_path=prereq_pattern,
                        )
                    )

    return findings


def _render_markdown(findings: list[dict]) -> str:
    """Render findings as a grouped Markdown report."""
    lines: list[str] = [
        "# Evidence Gap Report",
        "",
        f"Generated by `evidence_report.py`  |  {len(findings)} finding(s) total",
        "",
    ]

    # Group by flow_family
    by_family: dict[str, list[dict]] = {}
    for f in findings:
        by_family.setdefault(f["flow_family"], []).append(f)

    if not findings:
        lines.append("No issues found. All evidence requirements satisfied.")
        return "\n".join(lines)

    for family, flist in sorted(by_family.items()):
        lines += [
            f"## {family}",
            "",
            "| Case | Role | Issue | Path |",
            "|------|------|-------|------|",
        ]
        for f in flist:
            path_col = f["artifact_path"] or "—"
            lines.append(
                f"| {f['case_id']} | {f['role']} | **{f['issue']}** | {path_col} |"
            )
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Report missing, stale, and contradictory evidence across the validation catalog."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output JSON instead of Markdown",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit 1 if any MISSING or CONTRADICTORY findings exist",
    )
    parser.add_argument(
        "--stale-days",
        type=int,
        default=90,
        metavar="N",
        help="Files older than N days are flagged STALE (default: 90)",
    )
    parser.add_argument(
        "--catalog-root",
        default=None,
        metavar="PATH",
        help="Repo root path for resolving artifact paths (default: parent of scripts/)",
    )
    args = parser.parse_args()

    catalog_root = _resolve_catalog_root(args.catalog_root)

    # Ensure validation package is importable
    if str(catalog_root) not in sys.path:
        sys.path.insert(0, str(catalog_root))

    from validation.catalog import all_cases

    cases = list(all_cases())
    findings = collect_findings(cases, catalog_root, stale_days=args.stale_days)

    if args.json:
        print(json.dumps(findings, indent=2))
    else:
        print(_render_markdown(findings))

    if args.strict:
        severe = [f for f in findings if f["issue"] in ("MISSING", "CONTRADICTORY")]
        if severe:
            sys.exit(1)


if __name__ == "__main__":
    main()
