name: Compiling

on:
  # allows us to run workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MPICH_FC: gfortran

jobs:
  main:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Checkout repository nekStab
        uses: actions/checkout@v2
        
      - name: Checkout submodules Nek5000
        run: git submodule update --init --recursive
      
      - name: Install dependecies for Nek500 and NekStab
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y build-essential cmake 
          sudo apt install -y gfortran mpich libmpich-dev libopenblas-dev
         
      - name: Get cpu-information
        run: lscpu

      - name: Compile cylinder case
        shell: bash
        run: |
          cd Nek5000/tools
          ./maketools genmap genbox
          cd ../..          
          #pwd
          
          #export FC="mpif77"
          #export CC="mpicc"
          #export FFLAGS="-mcmodel=medium -march=native -ffixed-line-length-none"
          #export USR_LFLAGS+="-L/usr/lib -lopenblas"

          cd examples/cylinder/dns/
          export MAKEFLAGS="-j "`  lscpu | grep -i Thread | awk '{print $NF}' `
          #export NEKSTAB_SOURCE_ROOT="/home/runner/work/nekStab/nekStab"
          #export NEK_SOURCE_ROOT="$NEKSTAB_SOURCE_ROOT/Nek5000"
          #export FCcomp="gfotran"
          #source $NEKSTAB_SOURCE_ROOT/core/compiler_gcc_tb.sh
          #echo $FC
          #which mpif77
          ./cmpile.sh all
