# This is a basic workflow to help you get started with Actions

name: Compiling

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#     env: 
#       NEKSTAB_SOURCE_ROOT: ./
#       NEK_SOURCE_ROOT: $NEKSTAB_SOURCE_ROOT/Nek5000
#       MAKEFLAGS: "-j 2"

   # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Checkout repository nekStab
        uses: actions/checkout@v2
        
      - name: Checkout submodules Nek5000
        run: git submodule update --init --recursive
      
      - name: Install dependecies for Nek500 and NekStab
        run: sudo apt-get install gcc gfortran libmpich-dev libopenblas-dev
          
      - name: Get cpu-information
        run: lscpu

      #- uses: actions/github-script@v3
#       - name: Sourcing 
#         env:
#           NEKSTAB_SOURCE_ROOT: ./
#           NEK_SOURCE_ROOT: $NEKSTAB_SOURCE_ROOT/Nek5000
#           MAKEFLAGS: "-j 2"
#           FIRST_NAME: Mona
#           LAST_NAME: Octocat
#         with:
#           script: |
#             const { FIRST_NAME, LAST_NAME } = process.env

#             console.log(`Hello ${FIRST_NAME} ${LAST_NAME}`)
            
#      - name: Echoing paths...
#        run : echo $GITHUB_WORKSPACE
#              echo $WORKDIR
#              echo "$NEK_SOURCE_ROOT/bin" >> $GITHUB_PATH
#              echo $NEKSTAB_SOURCE_ROOT
#              echo $NEK_SOURCE_ROOT


      - name: Compile cylinder case
        run: |
         which mpif77
         which mpicc
         export CORES=$(sh sysctl -n hw.ncpu || echo 1)

         cd Nek5000/tools
         ./maketools genmap genbox
         cd ../..
         pwd
         cd examples/1cyl/autotest/base
         export MAKEFLAGS: "-j "$(CORES)
         echo $MAKEFLAGS
         export CASE="1cyl"
         export NEKSTAB_SOURCE_ROOT="../../../.." #--> path to nekStab
         export NEK_SOURCE_ROOT="$NEKSTAB_SOURCE_ROOT/Nek5000"
         export FFLAGS="-mcmodel=large -march=native -ffixed-line-length-none -g -fbacktrace"
         export USR_LFLAGS+="-L/usr/lib -lopenblas"
         source $NEKSTAB_SOURCE_ROOT/core/nekStab.sh
         $NEK_SOURCE_ROOT/bin/makenek $CASE
         more build.log

#         sh ./cmpile.sh all
         
     #git update-index --chmod +x for the whole repo
     #ROOT_DIR:
      #echo $NEKSTAB_SOURCE_ROOT
    #echo $NEK_SOURCE_ROOT
       #  ./cmpile.sh all
         
     ## - name: Running cylinder case
     #   run: |
    #     export CASE='1cyl'
    ##     export CASE_DIR=`pwd`
    #     echo $CASE > SESSION.NAME
   #      echo $CASE_DIR'/' >> SESSION.NAME
   #      mpiexec -np 2 ./nek5000
   ##      
   #   - name: Running cylinder case
   #     run: |
  #       export CASE='1cyl'
  #       export CASE_DIR=`pwd`
  #       echo $CASE > SESSION.NAME
  #       echo $CASE_DIR'/' >> SESSION.NAME
     #    mpiexec -np 2 ./nek5000

