# This is a basic workflow to help you get started with Actions

name: Compiling

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env: 
        CASE: "1cyl"
        NEKSTAB_SOURCE_ROOT: "../../../.." #--> path to nekStab
        NEK_SOURCE_ROOT: "$NEKSTAB_SOURCE_ROOT/Nek5000"
        FC: "mpif77"
        CC: "mpicc"
        FFLAGS: "-mcmodel=large -march=native -ffixed-line-length-none -g -fbacktrace"
      
   # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Checkout repository nekStab
        uses: actions/checkout@v2
        
      - name: Checkout submodules Nek5000
        run: git submodule update --init --recursive
      
      - name: Install dependecies for Nek500 and NekStab
        run: sudo apt-get install libmpich-dev libopenblas-dev
          
      - name: Get cpu-information
        run: lscpu

        # Export NEW_VAR_NAME variable for subsequent steps, and export all environment variables matching the optional regexp.
#       - uses: lukka/set-shell-env@v1
#         with:
#           CASE: "1cyl"
#           NEKSTAB_SOURCE_ROOT: "../../../.." #--> path to nekStab
#           NEK_SOURCE_ROOT: "$NEKSTAB_SOURCE_ROOT/Nek5000"
#           FC: "mpif77"
#           CC: "mpicc"
#           FFLAGS: "-mcmodel=large -march=native -ffixed-line-length-none -g -fbacktrace"
         
      # with:
      #   shell: 'bash' or 'tcsh' or any command that starts a shell.
      #   args: '-c env' or any arguments that list the environment variables as NAME=VALUE pairs.
      #   filter: an optional reg exp to export matching variables out of the desired shell.
      #   YOUR_VARIABLE_NAME: provide value for any new variable you name. Note the name will always be converted to be all uppercase.
      #  Here onward any following step can access the environment variable using:
      #  in your yml file:
      #     ${{ env.YOUR_VARIABLE_NAME }}
      - name: Compile cylinder case
        run: |
          pwd
          which mpif77
          which mpicc
          export MAKEFLAGS="-j "`  lscpu | grep -i Thread | awk '{print $NF}' `
          echo $MAKEFLAGS
          export USR_LFLAGS+="-L/usr/lib -lopenblas"
          echo $FC
          echo $CC
          cd Nek5000/tools
          ./maketools genmap genbox
          cd ../..
          pwd
          cd examples/1cyl/autotest/base
          source $NEKSTAB_SOURCE_ROOT/core/nekStab.sh
          sh ../../../../Nek5000/bin/makenek $CASE
          more build.log
  #        shell: bash

#         sh ./cmpile.sh all
         
     #git update-index --chmod +x for the whole repo
     #ROOT_DIR:
      #echo $NEKSTAB_SOURCE_ROOT
    #echo $NEK_SOURCE_ROOT
       #  ./cmpile.sh all
         
     ## - name: Running cylinder case
     #   run: |
    #     export CASE='1cyl'
    ##     export CASE_DIR=`pwd`
    #     echo $CASE > SESSION.NAME
   #      echo $CASE_DIR'/' >> SESSION.NAME
   #      mpiexec -np 2 ./nek5000
   ##      
   #   - name: Running cylinder case
   #     run: |
  #       export CASE='1cyl'
  #       export CASE_DIR=`pwd`
  #       echo $CASE > SESSION.NAME
  #       echo $CASE_DIR'/' >> SESSION.NAME
     #    mpiexec -np 2 ./nek5000

