name: GCC+MPICH
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MPICH_FC: gfortran
  MAKEFLAGS: "-j $(awk '/Thread/ {print $NF}' /proc/cpuinfo)"

jobs:
  main:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository nekStab
        uses: actions/checkout@v4

      - name: Execute Nek5000 Setup Script
        run: yes | ./Nek5000setup.sh

      - name: Compiling examples/cylinder/dns/
        run: |
          ./exports.sh
          cd examples/cylinder/dns/
          mks 1cyl
          nekmpi 1cyl 2