name: GCC build

on:
  # allows us to run workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MPICH_FC: gfortran

jobs:
  main:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Checkout repository nekStab
        uses: actions/checkout@v2
        
      - name: Checkout submodules Nek5000
        run: git submodule update --init --recursive
      
      - name: Install dependecies for Nek500 and NekStab
        shell: bash
        run: |
          sudo apt -y update
          #sudo apt install -y build-essential cmake 
          sudo apt install -y gfortran mpich libmpich-dev libopenblas-dev
      
      - name: Export parallel flag 
        shell: bash
        run: |
          lscpu
          export MAKEFLAGS="-j "`  lscpu | grep -i Thread | awk '{print $NF}' `
          
      - name: Compile nektools
        shell: bash
        run: |
          cd Nek5000/tools
          ./maketools genmap genbox
          cd ../..
          
      - name: Compiling examples/cylinder/dns/
        shell: bash
        run: |
          cd examples/cylinder/dns/
          ./cmpile.sh all
          cd ../../../

      - name: Compiling examples/cylinder/baseflow/
        shell: bash
        run: |
          cd examples/cylinder/baseflow/sfd
          ./cmpile.sh all
          cd ../newton
          ./cmpile.sh all
          cd ../boostconv
          cd ../../../../
  
      - name: Compiling examples/cylinder/stability/
        shell: bash
        run: |
          cd examples/cylinder/stability/direct
          ./cmpile.sh all
          cd ../adjoint
          ./cmpile.sh all
          cd ../../../../
          
      - name: Compiling examples/cylinder/sensitivity/
        shell: bash
        run: |
          cd examples/cylinder/sensitivity/wavemaker
          ./cmpile.sh all
          cd ../baseflow_sensitivity
          ./cmpile.sh all
          cd ../steady_force_sensitivity
          ./cmpile.sh all
          cd ../../../../
          
      - name: Compiling examples/cylinder/energy_budget/
        shell: bash
        run: |
          cd examples/cylinder/energy_budget/
          ./cmpile.sh all
          cd ../../../
