name: all compilers
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MPICH_FC: gfortran
  MAKEFLAGS: "-j $(awk '/Thread/ {print $NF}' /proc/cpuinfo)"

  jobs:
    test:
      runs-on: ${{ matrix.os }}
      continue-on-error: true
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          toolchain:
            - { compiler: gcc, version: 11 }
            - { compiler: intel-classic, version: "2021.10" }
          include:
            - os: ubuntu-latest
              toolchain: { compiler: intel, version: "2023.2" }
          exclude:
            - os: windows-latest
              toolchain: { compiler: intel-classic, version: "2021.10" }

      steps:
        - uses: awvwgk/setup-fortran@v1
          id: setup-fortran
          with:
            compiler: ${{ matrix.toolchain.compiler }}
            version: ${{ matrix.toolchain.version }}

        - run: ${{ env.FC }} --version
          env:
            FC: ${{ steps.setup-fortran.outputs.fc }}

        - name: Checkout repository nekStab
          uses: actions/checkout@v4

        - name: Execute Nek5000 Setup Script
          run: yes | ./Nek5000setup.sh

        - name: Compiling examples/cylinder/dns/
          run: |
            source exports.sh
            cd examples/cylinder/dns/
            mks 1cyl
            nekmpi 1cyl 2
