name: Intel OneAPI build

on:
  # allows us to run workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #MPICH_FC: gfortran

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash --noprofile --norc {0}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Intel OneApi repository
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update

      - name: Install Intel OneApi repository
        run: |
          sudo apt -y update
          sudo apt install -y gfortran libmpich-dev libopenblas-dev
          sudo apt -y install intel-oneapi-common-vars
          sudo apt -y install intel-oneapi-compiler-fortran
          sudo apt -y install intel-oneapi-mkl
          sudo apt -y install intel-oneapi-mpi
          sudo apt -y install intel-oneapi-mpi-devel
          source /opt/intel/oneapi/setvars.sh
          printenv >> $GITHUB_ENV

      - name: Checkout repository nekStab
        uses: actions/checkout@v2
        
      - name: Checkout submodules Nek5000
        run: git submodule update --init --recursive
      
      - name: Export parallel flag 
        shell: bash
        run: |
          lscpu
          export MAKEFLAGS="-j "`  lscpu | grep -i Thread | awk '{print $NF}' `
          
      - name: Compile nektools
        shell: bash
        run: |
          cd Nek5000/tools
          ./maketools genmap genbox
          cd ../..
          
      - name: Compiling examples/cylinder/dns/
        shell: bash
        run: |
          cd examples/cylinder/dns/
          ./cmpile.sh all
          nekmpi 1cyl 2